### PR TITLE
Replace charts with react components

### LINKED ISSUE #20: replace charts with react components
The current chart solution is deprecated and needs to be replaced by react components.

### PR DESCRIPTION
**Pull request by kamils-iRonin**
This closes #20 
image

~~This needs https://github.com/theforeman/foreman/pull/8228~~

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
If we could replace it with mounting the ChartBox components directly, it would make me very happy xD
We could then deprecate the flot_pie_chart more easily.

**Comment by ezr-ondrej** [comment]
Maybe we can have some rails helper for that, to simplify it if it would help, but I think here it should be pretty straight forward.

**Review by ezr-ondrej — APPROVED** [review]
Code-wise looks awesome to me! :+1:

**Comment by ezr-ondrej** [comment]
What is the status here? can we get this in?

**Comment by laugmanuel** [comment]
@kamils-iRonin can you give an update on this? And rebase if we still need/want this? 😉

**Comment by laugmanuel** [comment]
Closing as this is already done in https://github.com/theforeman/foreman_omaha/commit/a226b99b09bf2b37f72eb99fb64a49cab83fb239

**Comment by ezr-ondrej** [comment]
I belive it should go in :) `flot_pie_chart` is removed, so these charts just won't work now

**Comment by kamils-iRonin** [comment]
@laugmanuel rebased and updated the code a bit

**Comment by kamils-iRonin** [comment]
@laugmanuel do you mean the bar on the omaha group view page? if so, the link should be white 🤔 

image

**Comment by laugmanuel** [comment]
@kamils-iRonin , using Foreman 3.1 the link text is blue. The color attribute seems to come from `--pf-global--link--Color` - maybe it's just a Foreman 3.1 thing.
image

**Review by laugmanuel — APPROVED** [review]

**Comment by laugmanuel** [comment]
Thanks @kamils-iRonin

**Pull request merged**
