### PR TITLE
Fixes #29063 - use new ImporterRegistry to register ForemanOmaha

### PR DESCRIPTION
**Pull request by rahulbajaj0509**

### CODE REVIEW

**Comment by timogoebel** [comment]
@rahulbajaj0509: Thanks. What Foreman version does this require? Mind bumping `required foreman version` in `engine.rb`?

**Comment by rahulbajaj0509** [comment]
@timogoebel done! Let me know if anything else is required :)

**Comment by timogoebel** [comment]
@rahulbajaj0509: Sorry for the delay. Do you mind rebasing the PR?

**Comment by timogoebel** [comment]
I'll go ahead and merge this anyway. Thanks!

**Pull request merged**
