### PR TITLE
Use extend_template_helpers function to register renderer extension

### LINKED ISSUE #56: Error rendering the Flatcar Ignition Transpile template' error (NoMethodError): undefined method `transpile_container_linux_config'
Hi

After installing Omaha and trying to use the `transpile_container_linux_config` I'm getting this error
I can see from the Help section "Global methods (macros)" the macro should be available 

```bash
[root@foreman ~]# foreman-rake errors:fetch_log request_id=ea43b133
2021-09-16T22:22:25 [I|app|ea43b133] Started POST "/templates/provisioning_templates/174-Flatcar%20Ignition%20Transpile/preview?force_safemode=true" for 10.142.13.118 at 2021-09-16 22:22:25 +0200
2021-09-16T22:22:25 [I|app|ea43b133] Processing by ProvisioningTemplatesController#preview as JSON
2021-09-16T22:22:25 [I|app|ea43b133]   Parameters: {"template"=>"<%- ignition = snippet('Flatcar provision') -%>\n<%= transpile_container_linux_config(ignition) %>\n", "preview_host_id"=>51, "force_safemode"=>"true", "id"=>"174-Flatcar Ignition Transpile", "provisioning_template"=>{"template"=>"<%- ignition = snippet('Flatcar provision') -%>\n<%= transpile_container_linux_config(ignition) %>\n"}}
2021-09-16T22:22:26 [W|app|ea43b133] Error rendering the Flatcar Ignition Transpile template
2021-09-16T22:22:26 [I|app|ea43b133] Backtrace for 'Error rendering the Flatcar Ignition Transpile template' error (NoMethodError): undefined method `transpile_container_linux_config' for #<Foreman::Renderer::Scope::Provisioning:0x00007f5214063c78>
 ea43b133 | /usr/share/gems/gems/safemode-1.3.6/lib/safemode/scope.rb:37:in `method_missing'
 ea43b133 | Flatcar Ignition Transpile:53:in `bind'
 ea43b133 | /usr/share/gems/gems/safemode-1.3.6/lib/safemode.rb:51:in `eval'
 ea43b133 | /usr/share/gems/gems/safemode-1.3.6/lib/safemode.rb:51:in `eval'
 ea43b133 | /usr/share/foreman/lib/foreman/renderer/safe_mode_renderer.rb:7:in `render'
 ea43b133 | /usr/share/foreman/lib/foreman/renderer/base_renderer.rb:18:in `render'
 ea43b133 | /usr/share/foreman/app/models/template.rb:172:in `render'
 ea43b133 | /usr/share/foreman/app/controllers/templates_controller.rb:119:in `safe_render'
 ea43b133 | /usr/share/foreman/app/controllers/templates_controller.rb:99:in `preview'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:195:in `process_action'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
 ea43b133 | /usr/share/foreman/app/controllers/concerns/foreman/controller/timezone.rb:10:in `set_timezone'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 ea43b133 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 ea43b133 | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 ea43b133 | /usr/share/gems/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 ea43b133 | /usr/share/gems/gems/audited-4.9.0/lib/audited/sweeper.rb:14:in `around'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:139:in `run_callbacks'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:41:in `process_action'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/rescue.rb:22:in `process_action'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `block in instrument'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `instrument'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
 ea43b133 | /usr/share/gems/gems/activerecord-6.0.3.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:136:in `process'
 ea43b133 | /usr/share/gems/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:39:in `process'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:190:in `dispatch'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:254:in `dispatch'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:49:in `block in serve'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `each'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `serve'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:834:in `call'
 ea43b133 | /usr/share/gems/gems/apipie-dsl-2.4.0/lib/apipie_dsl/static_dispatcher.rb:67:in `call'
 ea43b133 | /usr/share/gems/gems/apipie-rails-0.5.17/lib/apipie/static_dispatcher.rb:66:in `call'
 ea43b133 | /usr/share/gems/gems/apipie-rails-0.5.17/lib/apipie/extractor/recorder.rb:137:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 ea43b133 | /usr/share/foreman/lib/foreman/middleware/telemetry.rb:10:in `call'
 ea43b133 | /usr/share/gems/gems/apipie-rails-0.5.17/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 ea43b133 | /usr/share/foreman/lib/foreman/middleware/catch_json_parse_errors.rb:9:in `call'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
 ea43b133 | /usr/share/foreman/lib/foreman/middleware/logging_context_session.rb:22:in `call'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/cookies.rb:648:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:101:in `run_callbacks'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 ea43b133 | /usr/share/gems/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:37:in `call_app'
 ea43b133 | /usr/share/gems/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:28:in `call'
 ea43b133 | /usr/share/gems/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 ea43b133 | /usr/share/foreman/lib/foreman/middleware/logging_context_request.rb:11:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/request_id.rb:27:in `call'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
 ea43b133 | /usr/share/gems/gems/activesupport-6.0.3.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
 ea43b133 | /usr/share/gems/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
 ea43b133 | /usr/share/gems/gems/secure_headers-6.3.0/lib/secure_headers/middleware.rb:11:in `call'
 ea43b133 | /usr/share/gems/gems/railties-6.0.3.7/lib/rails/engine.rb:527:in `call'
 ea43b133 | /usr/share/gems/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `public_send'
 ea43b133 | /usr/share/gems/gems/railties-6.0.3.7/lib/rails/railtie.rb:190:in `method_missing'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
 ea43b133 | /usr/share/gems/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
 ea43b133 | /usr/share/gems/gems/puma-5.3.2/lib/puma/configuration.rb:249:in `call'
 ea43b133 | /usr/share/gems/gems/puma-5.3.2/lib/puma/request.rb:77:in `block in handle_request'
 ea43b133 | /usr/share/gems/gems/puma-5.3.2/lib/puma/thread_pool.rb:338:in `with_force_shutdown'
 ea43b133 | /usr/share/gems/gems/puma-5.3.2/lib/puma/request.rb:76:in `handle_request'
 ea43b133 | /usr/share/gems/gems/puma-5.3.2/lib/puma/server.rb:438:in `process_client'
 ea43b133 | /usr/share/gems/gems/puma-5.3.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
 ea43b133 | /usr/share/gems/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2021-09-16T22:22:26 [I|app|ea43b133]   Rendering text template
2021-09-16T22:22:26 [I|app|ea43b133]   Rendered text template (Duration: 0.0ms | Allocations: 1)
2021-09-16T22:22:26 [I|app|ea43b133] Completed 500 Internal Server Error in 365ms (Views: 0.4ms | ActiveRecord: 17.4ms | Allocations: 135315)

Foreman version: 3.0.0
Plugins:
 - foreman-tasks 5.1.0
 - foreman_ansible 6.4.1
 - foreman_discovery 17.0.1
 - foreman_omaha 4.0.1
 - foreman_remote_execution 4.7.0
```

Template is pretty basic
```ruby
<%- ignition = snippet('Flatcar provision') -%>
<%= transpile_container_linux_config(ignition) %>
```

image

### PR DESCRIPTION
**Pull request by laugmanuel**
fixes #56

### CODE REVIEW

**Comment by timogoebel** [comment]
Looks good. We have confirmation, that this fixes the issue. CI needs a green light, though.

**Comment by laugmanuel** [comment]
> Looks good. We have confirmation, that this fixes the issue. CI needs a green light, though.

I'll open another PR to fix the pipeline and rebase this afterwards.

**Comment by timogoebel** [comment]
@laugmanuel: I belive we can rebase & merge this!

**Review by timogoebel — APPROVED** [review]

**Comment by laugmanuel** [comment]
I'm wondering if this is still technically needed? Testing with Foreman 3.0 and the recent fixes regarding Foreman >= 2.5, the template rendering now works without this modification here.

**Comment by timogoebel** [comment]
Thanks!

**Pull request merged**
